[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "git@github.com:tmux-plugins/tpm.git"
    refreshPeriod = "168h"

[".dircolors"]
    type = "file"
    url = "https://raw.githubusercontent.com/trapd00r/LS_COLORS/refs/heads/master/LS_COLORS"
    refreshPeriod = "168h"
