[".tmux/plugins/tmux-continuum"]
    type = "git-repo"
    url = "git@github.com:tmux-plugins/tmux-continuum.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-resurrect"]
    type = "git-repo"
    url = "git@github.com:tmux-plugins/tmux-resurrect.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-sensible"]
    type = "git-repo"
    url = "git@github.com:tmux-plugins/tmux-sensible.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-yank"]
    type = "git-repo"
    url = "git@github.com:tmux-plugins/tmux-yank.git"
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "git@github.com:tmux-plugins/tpm.git"
    refreshPeriod = "168h"

[".dircolors"]
    type = "file"
    url = "https://raw.githubusercontent.com/trapd00r/LS_COLORS/refs/heads/master/LS_COLORS"
    refreshPeriod = "168h"

[".zplug"]
    type = "git-repo"
    url = "git@github.com:zplug/zplug.git"
    refreshPeriod = "168h"

[".zprezto"]
    type = "git-repo"
    url = "git@github.com:sorin-ionescu/prezto.git"
    refreshPeriod = "168h"
